### ISSUE TITLE
Problems running it

### ISSUE THREAD

**Issue by demetere** [eva-robillard/NetsWithinNets2023#2]
Hello there I am trying to run your system but I am entirely lost. What is Renew, is it some java based project that I can get from somewhere? Thanks

**Comment by eva-robillard** [comment]
Hi ! Thank you for your interest. I saw you closed the issue, have you managed to get Renew and run the project ? Please come back to me if you need any help.

**Comment by demetere** [comment]
> Hi ! Thank you for your interest. I saw you closed the issue, have you managed to get Renew and run the project? Please come back to me if you need any help.

Hello There, thanks for the quick reply, I managed to somehow download the Renew, and I found in the paper that it was some tool, so right now I have a java error that says that Eval does not exist.

**Comment by eva-robillard** [comment]
Hello,

The process to run it is explained in the README file.

When the file is downloaded, you need to open the command invite in the repository and run "javac Eval.java". Next, from the same invite you must open Renew and the files you'll open on there will know Eval. I hope this is clear, please come back to me for any question (or I can make a video tutorial).

**Comment by demetere** [comment]
I have followed those steps, I executed `javac Eval.java`, and run the command `open system_net.rnw `, maybe the problem is Renew installation? I have downloaded the .dmg file for macros and just installed it with that. Do you think that this may cause the problem?

**Comment by eva-robillard** [comment]
After compiling Eval.java you should open the Renew app with the repository it is in, for example"C:\Users\....\renew2.6base\renew2.6\bin\win\renew" 

It should open the app and after within it you can open the file, not directly from the command invite.

**Comment by demetere** [comment]
amazing, so the problem was that I need to run that from that folder in order to find the Eval file correctly. Thanks for the information. 

I have a few questions, so should I ask you here or write you on email or any other way of communication.

**Comment by eva-robillard** [comment]
Yes ! I'm glad if you could finally make it work :) 

For other questions, please write to me at eva.robillard@ens-paris-saclay.fr
